sprites = ["Abigail.gif",
"Adol.gif",
"Aggretsuko.gif",
"Alice.gif",
"Angry Video Game Nerd.gif",
"Arcane.gif",
"Ark.gif",
"Arrghus.gif",
"Astronaut.gif",
"B.S. Boy.gif",
"B.S. Girl.gif",
"Baby Metroid.gif",
"Badeline.gif",
"Bananas In Pyjamas.gif",
"Bandit.gif",
"Batman.gif",
"Beau.gif",
"Bewp.gif",
"Big Key.gif",
"Birb.gif",
"Birdo.gif",
"Black Mage.gif",
"Blacksmith Link.gif",
"Blossom.gif",
"Bob.gif",
"Boo 2.gif",
"Boo.gif",
"Bottle o' Goo.gif",
"Bowser.gif",
"Branch.gif",
"Brian.gif",
"Broccoli.gif",
"Bronzor.gif",
"Bubbles.gif",
"Bullet Bill.gif",
"Buttercup.gif",
"Cactuar.gif",
"Cadence.gif",
"Captain Toadette.gif",
"CarlSagan42.gif",
"Casual Zelda.gif",
"Cat Boo.gif",
"CD-i Link.gif",
"Celes.gif",
"Charizard.gif",
"Cheep Cheep.gif",
"Chibity.gif",
"Cirno.gif",
"Clifford.gif",
"Clyde.gif",
"Conker.gif",
"Cornelius.gif",
"Cucco.gif",
"Cursor.gif",
"D.Owls.gif",
"Dark Boy.gif",
"Dark Girl.gif",
"Dark Link (Tunic).gif",
"Dark Link.gif",
"Dark Panda.gif",
"Dark Swatchy.gif",
"Dark Zelda.gif",
"Dark Zora.gif",
"Deadpool (Mythic).gif",
"Deadpool (SirCzah).gif",
"Deadrock.gif",
"Decidueye.gif",
"Demon Link.gif",
"Dragonite.gif",
"Drake The Dragon.gif",
"Eggplant.gif",
"EmoSaru.gif",
"Ezlo.gif",
"Fierce Deity Link.gif",
"Figaro Merchant.gif",
"Finn Merten.gif",
"Finny Bear.gif",
"Flavor Guy.gif",
"Floodgate Fish.gif",
"Four Swords Link.gif",
"Fox Link.gif",
"Frisk.gif",
"Frog Link.gif",
"Fujin.gif",
"Future Trunks.gif",
"Gamer.gif",
"Ganondorf.gif",
"Garfield.gif",
"Garnet.gif",
"Garo Master.gif",
"GBC Link.gif",
"Geno.gif",
"Gobli.gif",
"Goomba.gif",
"Goose.gif",
"GrandPOOBear.gif",
"Gruncle Stan.gif",
"Hardhat Beetle.gif",
"Hat Color Link.gif",
"Hat Kid.gif",
"Headless Link.gif",
"Hello Kitty.gif",
"Hidari.gif",
"Hint Tile.gif",
"Hitsuyan1337.gif",
"Hoarder (Bush).gif",
"Hoarder (Pot).gif",
"Hoarder (Rock).gif",
"Homer Simpson.gif",
"Hyrule Knight.gif",
"Hyrule Soldier.gif",
"iBazly.gif",
"Ignignokt.gif",
"Informant Woman.gif",
"Inkling.gif",
"Invisible Link.gif",
"Jack Frost.gif",
"Jason Frudnick.gif",
"Jasp.gif",
"Jogurt.gif",
"Katsura.gif",
"Kecleon.gif",
"Kenny McCormick.gif",
"Kholdstare.gif",
"King Gothalion.gif",
"King Graham v1.1.gif",
"Kirby.gif",
"Kore8.gif",
"Lakitu.gif",
"Lapras.gif",
"Lest.gif",
"Lily.gif",
"Linja.gif",
"Link.gif",
"Lucario.gif",
"Luigi.gif",
"Madeline.gif",
"Magus.gif",
"Maiden.gif",
"Mallow (Cat).gif",
"Manga Link.gif",
"Maple Queen.gif",
"Marin.gif",
"Mario (Classic).gif",
"Mario and Cappy.gif",
"Marisa Kirisame.gif",
"Marvin the Cat.gif",
"Matthias.gif",
"Meatwad.gif",
"Medallions.gif",
"Medli.gif",
"Megaman X.gif",
"MewLp.gif",
"Mike Jones.gif",
"Mini Ganon.gif",
"Minish Cap Link.gif",
"Minish Link.gif",
"missingno.gif",
"Modern Link.gif",
"Mog.gif",
"Momiji Inubashiri.gif",
"Moosh.gif",
"Mouse.gif",
"Ms. Paint Dog.gif",
"Nature Link.gif",
"Navi.gif",
"Negative Link.gif",
"Neosad.gif",
"NES Link.gif",
"Ness (Earthbound).gif",
"Nia.gif",
"Niko.gif",
"Old Man.gif",
"Ori.gif",
"Outline Link.gif",
"output.txt",
"Parallel Worlds Link.gif",
"Paula.gif",
"Penguin Link.gif",
"Pete (Harvest Moon).gif",
"Phoenix Wright.gif",
"Pikachu.gif",
"Pink Ribbon Link.gif",
"Piranha Plant.gif",
"Plague Knight.gif",
"Pokey.gif",
"Pony.gif",
"Popoi.gif",
"Poppy.gif",
"Porg Knight.gif",
"Power Up with Pride Mushroom.gif",
"Powerpuff Girl.gif",
"Pride Link.gif",
"Primm.gif",
"Princess Bubblegum.gif",
"Princess Peach.gif",
"Psyduck.gif",
"Purple Chest.gif",
"Pyro.gif",
"Rainbow Link.gif",
"Remeer.gif",
"Rick (Redacted).gif",
"Robo-Link 9000.gif",
"Rocko.gif",
"Rottytops.gif",
"Roy Koopa.gif",
"Rumia.gif",
"Rydia.gif",
"Ryu.gif",
"Sailor Moon.gif",
"Saitama.gif",
"Samus (Classic).gif",
"Samus (Super Metroid).gif",
"Samus.gif",
"Santa Link.gif",
"Scholar.gif",
"Selan.gif",
"SevenS1ns.gif",
"Shadow Sakura.gif",
"Shadow.gif",
"Shantae.gif",
"Shuppet.gif",
"Shy Guy.gif",
"SighnWaive.gif",
"SNES Controller.gif",
"Soda Can.gif",
"Solaire of Astora.gif",
"Sonic the Hedgehog.gif",
"Sora (KH1).gif",
"Sora.gif",
"Squall.gif",
"Squirrel.gif",
"Squirtle.gif",
"Stalfos.gif",
"Stan.gif",
"Static Link.gif",
"Stick Man.gif",
"Super Bomb.gif",
"Super Bunny.gif",
"Super Meat Boy.gif",
"Swatchy.gif",
"Tanooki Mario.gif",
"TASBot.gif",
"Tea Time.gif",
"Terra (Esper).gif",
"Tetra Sheet.gif",
"TGH.gif",
"The Pug.gif",
"Thief.gif",
"Thomcrow.gif",
"Tile.gif",
"Tingle.gif",
"TMNT.gif",
"Toad.gif",
"Toadette.gif",
"TotemLinks.gif",
"TP Zelda.gif",
"Trogdor the Burninator.gif",
"Tunic Color Link.gif",
"TwoFaced.gif",
"Ty the Tasmanian Tiger.gif",
"Ultros.gif",
"Untitled.gif",
"Valeera.gif",
"VanillaLink.gif",
"Vaporeon.gif",
"Vegeta.gif",
"Vera.gif",
"Vitreous.gif",
"Vivi.gif",
"Vivian.gif",
"Wario.gif",
"Will.gif",
"Wizzrobe.gif",
"Wolf Link (Festive).gif",
"Wolf Link (TP).gif",
"Yoshi.gif",
"Yunica Tovah.gif",
"Zandra.gif",
"Zebra Unicorn.gif",
"Zeckemyro.gif",
"Zelda.gif",
"Zero Suit Samus.gif",
"Zora.gif"]

window.onload = function() {
    for(var i = 0; i < sprites.length; ++i) {
        var sprite = sprites[i];
        var box = document.createElement("div");
        var name = sprite.slice(0, -4);
        var label = document.createTextNode("\n" + name);
        var img = document.createElement("img");
        img.src="spriteimgs/" + sprite;
        box.appendChild(img);
        box.appendChild(document.createElement("br"));
        box.appendChild(label);
        document.body.appendChild(box);
    }
}